version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  count-app:
    container_name: count-app.local
    image: count-app
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    build:
      context: .