on:
  push:
    branches:
      - main
permissions:
  contents: read  # This is required for actions/checkout
env:
  NODE_VERSION: 20.10.0
  NPM_VERSION: 9.8.1
jobs:
  docker:
    name: Execute tests and lints code
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-npm
      - name: Install deps
        run: npm i --frozen-lock
        shell: bash
      - name: Run unit tests
        run: npm run test
        shell: bash
      - name: Run lint code
        run: npm run lint
        shell: bash     